linters:
  enable:
  - gosec
  - unconvert
  - goconst
  - gocyclo
  - asciicheck
  - misspell
  - lll
  - unparam
  - dogsled
  - nakedret
  - prealloc
  - gocritic
  - godox
  - funlen
  - whitespace
  - gomnd
  - godot
  - nestif
  - nolintlint
  disable-all: false
  fast: false
