name: Build and run tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and run tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests and generate coverage
        uses: ./.github/actions/kubebuilder
      - name: Upload coverage results
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: coverage.html
